# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
    cloudrun: circleci/gcp-cloud-run@1.0.1
    sonarcloud: sonarsource/sonarcloud@1.1.1
    heroku: circleci/heroku@1.2.6
executors:
    gcloud-executor:
        docker:
            - image: google/cloud-sdk
    machine-executor:
        machine: true
jobs:
    build:
        description: Build the Project
        docker:
            - image: sugan1234/vaadinrepo:latest
        environment:
            MAVEN_CLI_OPTS: "--batch-mode"
        steps: 
            - checkout 
            - run: mvn $MAVEN_CLI_OPTS clean package -e 
            - store_artifacts: 
                path: target 
                destination: target
    test:
        description: Test the Project
        docker: 
            - image: sugan1234/vaadinrepo:latest 
        steps: 
            - checkout
            - run: mvn test -e 
            - run:
                name: Save test results
                command: |
                    mkdir -p ~/test-results/junit/
                    find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
                when: always
            - store_test_results:
                path: ~/test-results

            - store_artifacts: 
                path: reports 
                destination: reports

    static_code_analysis:
        description: Runs a static code analysis
        docker:
            # replace with your preferred image
            - image: sugan1234/vaadinrepo:latest
        steps:
            - checkout
            - run: mvn test -e 
            - run:
                name: Save test results
                command: |
                    mkdir -p ~/test-results/junit/
                    find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
                when: always
            - store_test_results:
                path: ~/test-results
            - run:
                name: Analyze on SonarCloud
                command: mvn verify sonar:sonar -Dsonar.projectKey=DIBSE-SoftwareEntwicklung2_daytrip2ski-api
workflows: 
    version: 2
    workflow: 
        jobs: 
        - build 
        - test: 
            requires: 
                - build
        - static_code_analysis:
            context: SonarCloud
            requires: 
                - build
        - heroku/deploy-via-git:
            requires:
                - test